export enum ActionType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RETRIVE = 'RETRIVE',
  ADD_DEVICE = 'ADD_DEVICE',
  REMOVE_DEVICE = 'REMOVE_DEVICE',
  SCHEDULE = 'SCHEDULE',
  ADD_USER = 'ADD_USER',
  DELETE_USER = 'DELETE_USER',
}
